### ISSUE TITLE
Change "namespace" references to "module"

### ISSUE THREAD

**Issue by mattrent** [funlessdev/fl-cli#105]
After the API refactor, the concept of namespace was renamed to module; both in flags and variable names, "namespace" and "ns" are still used instead of "module" and "mod". This should be fixed for consistency.

**Comment by ABrunoRaise** [comment]
Hi I'm try to get familiar with the code base and I would like to take on this issue. Is it okay?

**Comment by mattrent** [comment]
Sure, just fork the repo and open a PR when the code is ready!
