### ISSUE TITLE
Deployment over multiple nodes, with multiple replicas, should be supported

### ISSUE THREAD

**Issue by mattrent** [funlessdev/fl-cli#21]
Currently the only supported deployment configuration is 1 core + 1 worker on the same physical node.

Deployment over multiple nodes should be a separate option. 

It can be implemented using the docker swarm feature: see [swarm api](https://pkg.go.dev/github.com/docker/docker/client#SwarmAPIClient) and [swarm usage](https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/)

Perhaps the user should be able to run: `fl admin deploy core --advertise-addr="x.x.x.x"` 

After starting the swarm with the core deployed it should print out the join command with the token to use to perfom a docker swarm join (done via fl as well: `fl admin deploy worker --token ... --ip ...`)

**Comment by giusdp** [comment]
After checking out docker swarm to support multiple node deployment, it was decided to not use it anymore and start go for an ansible deployment to start and move to k8s after that.
