### ISSUE TITLE
Validation with supported languages

### ISSUE THREAD

**Issue by giusdp** [funlessdev/fl-cli#37]
When creating a function, the cli should do some validation to check if the code is supported. For now we could just check the extension of the file user. The current supported language is javascript, so we should accept only files ending in .js.

**Comment by mattrent** [comment]
As building from a single file is not currently supported, we should check for necessary files (e.g. `Cargo.toml` for Rust functions) in the source directory. In the future we will have to check extensions as well when not building from a directory.
